name: Unit Test

on:
  push:
    branches: [ "fix-*"]
  pull_request:
    branches: [ "fix-*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Unit test
      run: |
        mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        --batch-mode \
        --file pom.xml \
        --settings .github/workflows/settings.xml \
        --activate-profiles="GitHub Actions CI" \
        -Dskip.it=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
