name: Verify Product Quality

on:
  push:
    branches: [ "main", "develop-*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Google Chrome
      run: |
        $Path = $env:TEMP;
        $Installer = "chrome_installer.exe";
        Invoke-WebRequest "https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26browser%3D0%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26brand%3DGTPM/update2/installers/ChromeSetup.exe" `
          -OutFile $Path\$Installer;
        Start-Process -FilePath $Path\$Installer `
                      -Args "/silent /install" `
                      -Verb RunAs -Wait;
        Remove-Item $Path\$Installer

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v1

    - name: Verify Quality
      run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar `
        --batch-mode `
        --file pom.xml `
        --settings .github/workflows/settings.xml `
        --activate-profiles="GitHub Actions CI"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
